export default {
  sortAndFilterOptions: {
    showcaseSortOptions: [],
    showcaseFilterOptions: [],
  },
  showcases: {
    isFetching: true,
    list: [],
    count: "",
  },
  groupsAndViews: [],
  technologyList: {
    isFetching: true,
    list: [],
  },
  solutionListFiltersAndBrowseByRoles: {
    isFetching: true,
    columns: [],
    filterOptions: [],
    selectedFilters: {},
    browseByRoles: [],
  },
  solutionListFilterWithCount: [],
  myProfileData: {
    isFetching: true,
    details: {},
  },
  myTechnologies: {
    isFetching: true,
    list: [],
    count: "",
  },
  technologiesIFollow: {
    isFetching: true,
    list: [],
    count: "",
  },
  faqList: [],
  megaMenu: [],
  selectedGroup: "Default",
  selectedView: "All solutions",
  selectedMyRole: "All my roles",
  technologySummary: {
    isFetching: true,
    details: {},
  },
  techInfo: {
    isFetching: true,
    details: {},
  },
  tinyMCEKey: {
    value: "",
  },
  customerAndScheduleFilterOptions: {
    organization: "All",
    trl: "All",
    confirmIntent: "All",
    customerRepresentative: "",
    technicalContact: "",
    outcome: "All",
    confirmCompletion: "All",
    implementationStatus: "All",
    planStart: "",
    planCompletion: "",
    actualStart: "",
    actualCompletion: "",
    overviewStart: "",
    overviewCompleted: "",
    // Partial solution options
    partialOrganization: "All",
    partialTrl: "All",
    partialConfirmIntent: "All",
    partialCustomerRepresentative: "",
    partialTechnicalContact: "",
    partialOutcome: "All",
    partialConfirmCompletion: "All",
    partialImplementationStatus: "All",
    partialPlanStart: "",
    partialPlanCompletion: "",
    partialActualStart: "",
    partialActualCompletion: "",
    partialOverviewStart: "",
    partialOverviewCompleted: "",
  },
};
